name: Build macOS App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Install Node.js
        uses: actions/setup-node@v4 # Actualizado a v4
        with:
          node-version: 20 # Actualizado a una versión de Node más reciente

      - name: Install Dependencies
        run: npm install

      - name: Build App for Mac
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4 # ¡Esta es la corrección importante!
        with:
          name: Mac-Installer
          path: release/*.dmg
